# Generated by Django 5.1.7 on 2025-04-22 04:20

import communication.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('message_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=communication.models.media_upload_path)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='communication.message')),
            ],
            options={
                'db_table': 'message_media',
            },
        ),
    ]
