# Generated by Django 5.1.7 on 2025-04-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('forward_phone_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('date_paid', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('url', models.TextField(max_length=255)),
                ('stripe_invoice_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('invoice_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('amount_percentage', models.FloatField()),
            ],
            options={
                'db_table': 'invoice_type',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('opt_in_text_messaging', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'db_table': 'lead',
            },
        ),
        migrations.CreateModel(
            name='LeadInterest',
            fields=[
                ('lead_interest_id', models.IntegerField(primary_key=True, serialize=False)),
                ('interest', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeadNextAction',
            fields=[
                ('lead_next_action_id', models.IntegerField(primary_key=True, serialize=False)),
                ('action_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('lead_note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'lead_note',
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('lead_status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NextAction',
            fields=[
                ('next_action_id', models.IntegerField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('guests', models.IntegerField()),
                ('hours', models.FloatField()),
                ('event_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'quote',
            },
        ),
        migrations.CreateModel(
            name='QuoteService',
            fields=[
                ('quote_service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('units', models.FloatField()),
                ('price_per_unit', models.FloatField()),
            ],
            options={
                'db_table': 'quote_service',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('suggested_price', models.FloatField(null=True)),
                ('guest_ratio', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('service_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'service_type',
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('unit_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'unit_type',
            },
        ),
    ]
