# Generated by Django 5.1.7 on 2025-04-13 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='staff', through='crm.EventStaff', to='crm.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.ForeignKey(db_column='invoice_type_id', on_delete=django.db.models.deletion.RESTRICT, to='core.invoicetype'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_interest',
            field=models.ForeignKey(db_column='lead_interest_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadinterest'),
        ),
        migrations.AddField(
            model_name='leadnextaction',
            name='lead',
            field=models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, to='core.lead'),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='lead',
            field=models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.lead'),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='user',
            field=models.ForeignKey(db_column='added_by_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.ForeignKey(db_column='lead_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stauses', to='core.leadstatus'),
        ),
        migrations.AddField(
            model_name='leadnextaction',
            name='next_action',
            field=models.ForeignKey(db_column='next_action_id', on_delete=django.db.models.deletion.CASCADE, to='core.nextaction'),
        ),
        migrations.AddField(
            model_name='lead',
            name='actions',
            field=models.ManyToManyField(related_name='actions', through='core.LeadNextAction', to='core.nextaction'),
        ),
        migrations.AddField(
            model_name='quote',
            name='lead',
            field=models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.lead'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(db_column='quote_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.quote'),
        ),
        migrations.AddField(
            model_name='quoteservice',
            name='quote',
            field=models.ForeignKey(db_column='quote_id', on_delete=django.db.models.deletion.RESTRICT, related_name='quote_services', to='core.quote'),
        ),
        migrations.AddField(
            model_name='quoteservice',
            name='service',
            field=models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.RESTRICT, to='core.service'),
        ),
        migrations.AddField(
            model_name='quote',
            name='services',
            field=models.ManyToManyField(related_name='quote_services', through='core.QuoteService', to='core.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(db_column='service_type_id', on_delete=django.db.models.deletion.RESTRICT, to='core.servicetype'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_type',
            field=models.ForeignKey(db_column='unit_type_id', on_delete=django.db.models.deletion.RESTRICT, to='core.unittype'),
        ),
    ]
