# Generated by Django 5.1.7 on 2025-05-15 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltracking',
            name='click_id',
        ),
        migrations.RemoveField(
            model_name='calltracking',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='calltrackingnumber',
            name='marketing_campaign',
        ),
        migrations.AddField(
            model_name='calltracking',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='calltracking',
            name='call_tracking_number',
            field=models.ForeignKey(db_column='call_tracking_number_id', on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.calltrackingnumber'),
        ),
        migrations.AlterField(
            model_name='calltracking',
            name='external_id',
            field=models.CharField(max_length=255),
        ),
    ]
