# Generated by Django 5.1.7 on 2025-05-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='name',
            field=models.TextField(default='fb'),
            preserve_default=False,
        ),
    ]
