# Generated by Django 5.1.7 on 2025-05-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPage',
        ),
        migrations.AlterModelTable(
            name='leadinterest',
            table='lead_interest',
        ),
        migrations.AlterModelTable(
            name='leadnextaction',
            table='lead_next_action',
        ),
        migrations.AlterModelTable(
            name='leadstatus',
            table='lead_status',
        ),
        migrations.AlterModelTable(
            name='leadstatushistory',
            table='lead_status_history',
        ),
        migrations.AlterModelTable(
            name='marketingcampaign',
            table='marketing_campaign',
        ),
        migrations.AlterModelTable(
            name='nextaction',
            table='next_action',
        ),
    ]
