# Generated by Django 5.1.7 on 2025-05-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_landingpage_alter_leadinterest_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadstatus',
            name='updated_at',
        ),
    ]
