# Generated by Django 5.1.7 on 2025-04-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lead_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stripe_customer_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
