# Generated by Django 5.1.7 on 2025-05-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_leadstatus_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventcocktail',
            name='event_cocktail_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventrole',
            name='event_role_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventstaff',
            name='event_staff_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoicetype',
            name='invoice_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadinterest',
            name='lead_interest_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadnextaction',
            name='lead_next_action_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='lead_note_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='lead_status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='status',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('INVOICE_SENT', 'Invoice Sent'), ('EVENT_BOOKED', 'Event Booked')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nextaction',
            name='next_action_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='quote_service_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='unit_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['text_from'], name='message_text_fr_adb9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['text_to'], name='message_text_to_4eb4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='message_is_read_8eefe1_idx'),
        ),
    ]
