# Generated by Django 5.1.7 on 2025-05-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cocktail_cocktail_id_alter_event_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cocktails',
            new_name='cocktail',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='event',
            field=models.ManyToManyField(related_name='cocktails', through='core.EventCocktail', to='core.event'),
        ),
    ]
