# Generated by Django 5.1.7 on 2025-05-26 04:08

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_cocktails_event_cocktail_cocktail_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='event',
        ),
        migrations.AddField(
            model_name='eventstaff',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 12, 12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventstaff',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 11, 0)),
            preserve_default=False,
        ),
    ]
