# Generated by Django 5.1.7 on 2025-05-27 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cocktail_event_eventstaff_end_time_and_more'),
    ]

    operations = []
