# Generated by Django 5.1.7 on 2025-05-27 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ingredient_unit_cocktailingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('cocktail', models.ForeignKey(db_column='cocktail_id', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.cocktail')),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_cocktails', to='core.ingredient')),
                ('unit', models.ForeignKey(db_column='unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_cocktails', to='core.unit')),
            ],
            options={
                'db_table': 'cocktail_ingredient',
                'unique_together': {('cocktail', 'ingredient', 'unit')},
            },
        ),
    ]
