# Generated by Django 5.1.7 on 2025-05-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_populate_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailingredient',
            name='id',
        ),
        migrations.AddField(
            model_name='cocktailingredient',
            name='cocktail_ingredient_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
