# Generated by Django 5.1.7 on 2025-05-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_cocktailingredient_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('ingredient_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ingredient_category',
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_category',
            field=models.ForeignKey(db_column='ingredient_category_id', on_delete=django.db.models.deletion.CASCADE, to='core.ingredientcategory'),
            preserve_default=False,
        ),
    ]
