# Generated by Django 5.1.7 on 2025-05-28 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ingredientcategory_remove_ingredient_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='special_instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='street_address_two',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='ingredient',
            field=models.ForeignKey(db_column='ingredient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ingredient'),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='unit',
            field=models.ForeignKey(db_column='unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_category',
            field=models.ForeignKey(db_column='ingredient_category_id', on_delete=django.db.models.deletion.RESTRICT, to='core.ingredientcategory'),
        ),
        migrations.CreateModel(
            name='EventShoppingList',
            fields=[
                ('event_shopping_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event', models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='core.event')),
            ],
            options={
                'db_table': 'event_shopping_list',
            },
        ),
        migrations.CreateModel(
            name='EventShoppingListEntry',
            fields=[
                ('event_shopping_list_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.TextField()),
                ('quantity', models.FloatField()),
                ('event_shopping_list', models.ForeignKey(db_column='event_shopping_list_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.eventshoppinglist')),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.RESTRICT, to='core.unit')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='store',
            field=models.ForeignKey(db_column='store_id', default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.store'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('unit_conversion_id', models.AutoField(primary_key=True, serialize=False)),
                ('multiplier', models.FloatField()),
                ('from_unit', models.ForeignKey(db_column='from_unit', on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions_from', to='core.unit')),
                ('to_unit', models.ForeignKey(db_column='to_unit', on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions_to', to='core.unit')),
            ],
            options={
                'db_table': 'unit_conversion',
            },
        ),
    ]
