# Generated by Django 5.1.7 on 2025-05-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_eventshoppinglistentry_store'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventshoppinglistentry',
            table='event_shopping_list_entry',
        ),
    ]
