# Generated by Django 5.1.7 on 2025-05-28 19:44

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_eventshoppinglistentry_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventshoppinglistentry',
            name='item',
        ),
        migrations.RemoveField(
            model_name='eventshoppinglistentry',
            name='store',
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('store_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to=core.utils.media_upload_path)),
                ('product_quantity', models.FloatField()),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.RESTRICT, to='core.store')),
            ],
            options={
                'db_table': 'store_item',
            },
        ),
        migrations.AddField(
            model_name='eventshoppinglistentry',
            name='store_item',
            field=models.ForeignKey(db_column='store_item_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.storeitem'),
            preserve_default=False,
        ),
    ]
