# Generated by Django 5.1.7 on 2025-05-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_eventshoppinglistentry_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
