# Generated by Django 5.1.7 on 2025-05-28 19:53

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_storeitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='unit',
            field=models.ForeignKey(db_column='unit_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.unit'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(null=True, upload_to=core.utils.media_upload_path),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='product_quantity',
            field=models.FloatField(null=True),
        ),
    ]
