# Generated by Django 5.1.7 on 2025-05-28 20:05

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_storeitem_unit_alter_storeitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.FileField(null=True, upload_to=core.utils.media_upload_path),
        ),
    ]
