# Generated by Django 5.1.7 on 2025-05-30 00:38

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_storeitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(null=True, upload_to=core.utils.save_image_path),
        ),
        migrations.AlterUniqueTogether(
            name='cocktailingredient',
            unique_together={('cocktail', 'ingredient')},
        ),
        migrations.AddConstraint(
            model_name='eventshoppinglistentry',
            constraint=models.UniqueConstraint(fields=('event_shopping_list', 'store_item'), name='unique_store_item_per_event_shopping_list'),
        ),
    ]
