# Generated by Django 5.1.7 on 2025-05-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_storeitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='type',
            field=models.CharField(default='Bottle', max_length=255),
            preserve_default=False,
        ),
    ]
