# Generated by Django 5.1.7 on 2025-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_storeitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltrackingnumber',
            name='call_tracking_number',
        ),
        migrations.AddField(
            model_name='calltrackingnumber',
            name='forward_phone_number',
            field=models.CharField(default='3052830692', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calltrackingnumber',
            name='phone_number',
            field=models.CharField(default='7869987919', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadmarketing',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='status',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('INVOICE_SENT', 'Invoice Sent'), ('EVENT_BOOKED', 'Event Booked'), ('RE_ENGAGED', 'Re-Engaged')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='calltrackingnumber',
            table='phone_number',
        ),
    ]
