# Generated by Django 5.1.7 on 2025-05-31 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_lead_full_name_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantform',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadmarketing',
            name='instant_form',
            field=models.ForeignKey(db_column='instant_form_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.instantform'),
        ),
        migrations.AlterField(
            model_name='leadmarketing',
            name='instant_form_lead_id',
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leadmarketing',
            name='marketing_campaign',
            field=models.ForeignKey(db_column='marketing_campaign_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.marketingcampaign'),
        ),
    ]
