# Generated by Django 5.1.7 on 2025-05-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_instantform_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmarketing',
            name='instant_form',
        ),
        migrations.AddField(
            model_name='leadmarketing',
            name='instant_form_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='InstantForm',
        ),
    ]
