# Generated by Django 5.1.7 on 2025-06-01 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_leadmarketing_instant_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httplog',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='status',
            field=models.CharField(choices=[('LEAD_CREATED', 'LEAD_CREATED'), ('INVOICE_SENT', 'INVOICE_SENT'), ('EVENT_BOOKED', 'EVENT_BOOKED'), ('RE_ENGAGED', 'RE_ENGAGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='lead_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.leadstatus'),
        ),
    ]
