# Generated by Django 5.1.7 on 2025-06-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_httplog_url_alter_leadstatus_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httplog',
            name='error',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httplog',
            name='query_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httplog',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httplog',
            name='service_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
