# Generated by Django 5.1.7 on 2025-06-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_httplog_error_alter_httplog_query_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmarketing',
            name='user_agent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
