# Generated by Django 5.1.7 on 2025-06-03 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_leadmarketing_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_invoice_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='calltracking',
            name='external_id',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eventshoppinglist',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leadmarketing',
            name='external_id',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='external_id',
            field=models.CharField(db_index=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='phonecall',
            name='external_id',
            field=models.CharField(db_index=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='phonecalltranscription',
            name='external_id',
            field=models.CharField(db_index=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='external_id',
            field=models.UUIDField(editable=False),
        ),
    ]
