# Generated by Django 5.1.7 on 2025-06-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_quotepreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotepreset',
            name='preset',
        ),
        migrations.CreateModel(
            name='QuotePresetService',
            fields=[
                ('quote_preset_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_preset', models.ForeignKey(db_column='quote_preset_id', on_delete=django.db.models.deletion.CASCADE, to='core.quotepreset')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.RESTRICT, to='core.service')),
            ],
            options={
                'db_table': 'quote_preset_service',
            },
        ),
        migrations.AddField(
            model_name='quotepreset',
            name='services',
            field=models.ManyToManyField(related_name='services', through='core.QuotePresetService', to='core.service'),
        ),
        migrations.AddConstraint(
            model_name='quotepresetservice',
            constraint=models.UniqueConstraint(fields=('quote_preset', 'service'), name='unique_quote_preset_service'),
        ),
    ]
