# Generated by Django 5.1.7 on 2025-06-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_quotepreset_preset_quotepresetservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_paid',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetype',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('REMAINING', 'REMAINING'), ('FULL', 'FULL')], max_length=50),
        ),
    ]
