# Generated by Django 5.1.7 on 2025-06-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_facebookaccesstoken_rename_url_invoice_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmarketing',
            name='external_id',
            field=models.UUIDField(db_index=True, editable=False, null=True, unique=True),
        ),
    ]
