# Generated by Django 5.1.7 on 2025-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_leadmarketing_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='stripe_customer_id',
        ),
        migrations.AlterField(
            model_name='invoicetype',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('REMAINING', 'REMAINING'), ('FULL', 'FULL'), ('EXTEND', 'EXTEND')], db_index=True, max_length=50, unique=True),
        ),
    ]
