# Generated by Django 5.1.7 on 2025-06-17 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_lead_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receipt',
            field=models.FileField(null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='quoteservice',
            name='quote',
            field=models.ForeignKey(db_column='quote_id', on_delete=django.db.models.deletion.CASCADE, related_name='quote_services', to='core.quote'),
        ),
    ]
