# Generated by Django 5.1.7 on 2025-06-17 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_invoice_receipt_alter_quoteservice_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('logger', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('pathname', models.TextField(null=True)),
                ('lineno', models.IntegerField(null=True)),
                ('exception', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='leadmarketing',
            name='referred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.leadmarketing'),
        ),
    ]
