# Generated by Django 5.1.7 on 2025-06-17 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_internallog_leadmarketing_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.BigIntegerField()),
                ('name', models.TextField()),
                ('platform_id', models.IntegerField(choices=[(1, 'Google'), (2, 'Facebook')])),
            ],
            options={
                'db_table': 'ad',
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_campaign_id', models.BigIntegerField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'ad_campaign',
            },
        ),
        migrations.RemoveField(
            model_name='leadmarketing',
            name='marketing_campaign',
        ),
        migrations.AlterField(
            model_name='calltracking',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='leadmarketing',
            name='ad',
            field=models.ForeignKey(db_column='ad_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.ad'),
        ),
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_group_id', models.BigIntegerField()),
                ('name', models.TextField()),
                ('ad_campaign', models.ForeignKey(db_column='ad_campaign_id', on_delete=django.db.models.deletion.RESTRICT, related_name='ad_groups', to='core.adcampaign')),
            ],
            options={
                'db_table': 'ad_group',
                'unique_together': {('ad_group_id', 'ad_campaign_id')},
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_group',
            field=models.ForeignKey(db_column='ad_group_id', on_delete=django.db.models.deletion.RESTRICT, related_name='ads', to='core.adgroup'),
        ),
        migrations.DeleteModel(
            name='MarketingCampaign',
        ),
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('ad_id', 'platform_id')},
        ),
    ]
