# Generated by Django 5.1.7 on 2025-06-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_ad_adcampaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='calltrackingnumber',
            table='call_tracking_number',
        ),
    ]
