# Generated by Django 5.1.7 on 2025-06-18 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_ad_name_alter_calltrackingnumber_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='internallog',
            table='internal_log',
        ),
    ]
