# Generated by Django 5.1.7 on 2025-06-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_internallog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltrackingnumber',
            name='date_expires',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
