# Generated by Django 5.1.7 on 2025-06-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_calltrackingnumber_date_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('reviewer_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewer_profile_photo_url', models.URLField(blank=True, null=True)),
                ('star_rating', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('location_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'google_review',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['external_id'], name='google_revi_externa_73bc51_idx'), models.Index(fields=['location_id'], name='google_revi_locatio_6e276d_idx')],
            },
        ),
    ]
