# Generated by Django 5.1.7 on 2025-06-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_googlereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereview',
            name='rating_value',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
