# Generated by Django 5.1.7 on 2025-07-02 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_googlereview_rating_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmarketing',
            name='button_clicked',
        ),
        migrations.AlterField(
            model_name='calltrackingnumber',
            name='date_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 2, 18, 12, 43, 639638, tzinfo=datetime.timezone.utc)),
        ),
    ]
