# Generated by Django 5.1.7 on 2025-07-02 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_leadmarketing_button_clicked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltrackingnumber',
            name='date_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 2, 18, 13, 30, 361943, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referrer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='url',
            field=models.TextField(),
        ),
    ]
