# Generated by Django 5.1.7 on 2025-07-02 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_calltrackingnumber_date_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltracking',
            name='external_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='calltrackingnumber',
            name='date_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
