# Generated by Django 5.1.7 on 2025-07-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_calltracking_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
    ]
