# Generated by Django 5.1.7 on 2025-07-06 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_lead_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmarketing',
            name='referrer',
        ),
        migrations.AlterField(
            model_name='facebookaccesstoken',
            name='date_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
