# Generated by Django 5.1.7 on 2025-07-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_leadmarketing_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereview',
            name='should_show',
            field=models.BooleanField(default=False),
        ),
    ]
