# Generated by Django 5.1.7 on 2025-07-08 03:38

from django.db import migrations

def seed_unit_and_service_types(apps, schema_editor):
    UnitType = apps.get_model('core', 'UnitType')
    ServiceType = apps.get_model('core', 'ServiceType')

    unit_types = ['Per Person', 'Hourly', 'Fixed']
    service_types = ['Service', 'Rental', 'Food', 'Add On', 'Entertainment', 'Extend']

    for unit in unit_types:
        UnitType.objects.get_or_create(type=unit)

    for service in service_types:
        ServiceType.objects.get_or_create(type=service)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_servicetype_type_alter_unittype_type'),
    ]

    operations = [
        migrations.RunPython(seed_unit_and_service_types),
    ]