# Generated by Django 5.1.7 on 2025-07-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20250707_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmarketing',
            name='user_agent',
            field=models.TextField(null=True),
        ),
    ]
