# Generated by Django 5.1.7 on 2025-07-17 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_phonecallstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccessToken',
            fields=[
                ('google_access_token_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(blank=True, max_length=50, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('date_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'google_access_token',
            },
        ),
    ]
