# Generated by Django 5.1.7 on 2025-07-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_googleaccesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleaccesstoken',
            name='token_type',
        ),
    ]
