# Generated by Django 5.1.7 on 2025-07-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_googleaccesstoken_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_from',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_to',
            field=models.CharField(max_length=15),
        ),
    ]
