# Generated by Django 5.1.7 on 2025-07-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_message_text_from_alter_message_text_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecall',
            name='call_from',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='phonecall',
            name='call_to',
            field=models.CharField(max_length=15),
        ),
    ]
