# Generated by Django 5.1.7 on 2025-07-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_phonecall_call_from_alter_phonecall_call_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
