# Generated by Django 5.1.7 on 2025-07-24 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecall',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phonecalltranscription',
            name='phone_call',
            field=models.OneToOneField(db_column='phone_call_id', on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='core.phonecall'),
        ),
    ]
