# Generated by Django 5.1.7 on 2025-08-02 03:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_phonecall_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmarketing',
            name='ad',
            field=models.ForeignKey(db_column='ad_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='leads', to='core.ad'),
        ),
        migrations.CreateModel(
            name='LeadMarketingMetadata',
            fields=[
                ('lead_marketing_metadata_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_marketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.leadmarketing')),
            ],
            options={
                'db_table': 'lead_marketing_metadata',
                'constraints': [models.UniqueConstraint(fields=('lead_marketing', 'key'), name='unique_lead_marketing_key')],
            },
        ),
    ]
