# Generated by Django 5.1.7 on 2025-08-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_leadmarketing_ad_leadmarketingmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmarketing',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='leadmarketing',
            name='click_id',
        ),
        migrations.RemoveField(
            model_name='leadmarketing',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='leadmarketing',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='leadmarketing',
            name='landing_page',
        ),
        migrations.RemoveField(
            model_name='leadmarketing',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='leadmarketing',
            name='source',
        ),
    ]
