# Generated by Django 5.1.7 on 2025-08-07 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_leadmarketing_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='phonecall',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
