# Generated by Django 5.1.7 on 2025-08-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_message_text_alter_phonecall_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
