# Generated by Django 5.1.7 on 2025-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_message_is_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecalltranscription',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
