# Generated by Django 5.1.7 on 2025-08-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_phonecalltranscription_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='guests',
            new_name='adults',
        ),
        migrations.AddField(
            model_name='quote',
            name='minors',
            field=models.IntegerField(null=True),
        ),
    ]
