# Generated by Django 5.1.7 on 2025-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_rename_guests_quote_adults_quote_minors'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecall',
            name='parent_id',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
