# Generated by Django 5.1.7 on 2025-09-10 04:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_phonecall_parent_id_alter_servicetype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltrackingnumber',
            name='date_expires',
        ),
        migrations.AddField(
            model_name='calltrackingnumber',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('landing_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('template_name', models.CharField(max_length=255, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('tracking_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='landing_pages', to='core.calltrackingnumber')),
            ],
            options={
                'db_table': 'landing_page',
            },
        ),
        migrations.CreateModel(
            name='LandingPageConversion',
            fields=[
                ('landing_page_conversion_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('conversion_type', models.CharField(choices=[('phone_call', 'Phone Call'), ('form_submission', 'Form Submission')], default='form_submission', max_length=20)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conversions', to='core.landingpage')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.lead')),
            ],
            options={
                'db_table': 'landing_page_conversion',
            },
        ),
        migrations.DeleteModel(
            name='CallTracking',
        ),
        migrations.AddConstraint(
            model_name='landingpage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_landing_page'),
        ),
    ]
