# Generated by Django 5.1.7 on 2025-09-10 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_calltrackingnumber_date_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='landing_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='visits', to='core.landingpage'),
        ),
    ]
