# Generated by Django 5.1.7 on 2025-09-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_visit_landing_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltrackingnumber',
            name='date_assigned',
        ),
    ]
