# Generated by Django 5.1.7 on 2025-09-11 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_calltrackingnumber_date_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='tracking_number',
        ),
        migrations.CreateModel(
            name='LandingPageTrackingNumber',
            fields=[
                ('landing_page_phone_number_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('call_tracking_number', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tracking_numbers', to='core.calltrackingnumber')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tracking_numbers', to='core.landingpage')),
            ],
            options={
                'db_table': 'landing_page_tracking_number',
            },
        ),
    ]
