# Generated by Django 5.1.7 on 2025-09-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_remove_landingpage_tracking_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='landingpage',
            name='unique_default_landing_page',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='is_default',
        ),
    ]
