# Generated by Django 5.1.7 on 2025-09-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_remove_landingpage_unique_default_landing_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='is_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='landingpage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_control', True)), fields=('is_active', 'is_control'), name='unique_active_control_lp'),
        ),
    ]
