# Generated by Django 5.1.7 on 2025-09-26 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_landingpage_is_control_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingPhoneCall',
            fields=[
                ('tracking_phone_call_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('call_duration', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_from', models.CharField(max_length=15)),
                ('call_to', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tracking_phone_call',
            },
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='status',
            field=models.CharField(choices=[('LEAD_CREATED', 'LEAD_CREATED'), ('INVOICE_SENT', 'INVOICE_SENT'), ('EVENT_BOOKED', 'EVENT_BOOKED'), ('RE_ENGAGED', 'RE_ENGAGED'), ('ARCHIVED', 'ARCHIVED')], max_length=50),
        ),
        migrations.CreateModel(
            name='TrackingPhoneCallMetadata',
            fields=[
                ('tracking_phone_call_metadata_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tracking_phone_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.trackingphonecall')),
            ],
            options={
                'db_table': 'tracking_phone_call_metadata',
                'constraints': [models.UniqueConstraint(fields=('tracking_phone_call', 'key'), name='unique_phone_call_key')],
            },
        ),
    ]
