# Generated by Django 5.1.7 on 2025-09-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_trackingphonecall_alter_leadstatus_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trackingphonecallmetadata',
            name='unique_phone_call_key',
        ),
        migrations.AddConstraint(
            model_name='trackingphonecallmetadata',
            constraint=models.UniqueConstraint(fields=('tracking_phone_call', 'key'), name='unique_phone_call_key'),
        ),
    ]
