# Generated by Django 5.1.7 on 2025-09-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_trackingphonecallmetadata_unique_phone_call_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trackingphonecallmetadata',
            name='unique_phone_call_key',
        ),
    ]
