# Generated by Django 5.1.7 on 2025-09-26 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_trackingphonecallmetadata_unique_phone_call_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingTextMessage',
            fields=[
                ('tracking_text_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('message', models.TextField()),
                ('text_from', models.CharField(max_length=15)),
                ('text_to', models.CharField(max_length=15)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tracking_text_message',
            },
        ),
        migrations.CreateModel(
            name='TrackingTextMessageMetadata',
            fields=[
                ('tracking_text_message_metadata_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tracking_text_message_metadata',
            },
        ),
        migrations.AddConstraint(
            model_name='trackingphonecallmetadata',
            constraint=models.UniqueConstraint(fields=('tracking_phone_call', 'key'), name='unique_tracking_phone_call_key'),
        ),
        migrations.AddField(
            model_name='trackingtextmessagemetadata',
            name='tracking_text_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.trackingtextmessage'),
        ),
        migrations.AddConstraint(
            model_name='trackingtextmessagemetadata',
            constraint=models.UniqueConstraint(fields=('tracking_text_message', 'key'), name='unique_tracking_text_message_key'),
        ),
    ]
