# Generated by Django 5.1.7 on 2025-09-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_trackingtextmessage_trackingtextmessagemetadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingtextmessage',
            name='status',
        ),
    ]
