# Generated by Django 5.1.7 on 2025-09-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_sessionmapping'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sessionmapping',
            table='session_mapping',
        ),
    ]
