# Generated by Django 5.1.7 on 2025-10-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_sessionmapping_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='cookies',
            field=models.JSONField(default=dict),
        ),
    ]
