# Generated by Django 5.1.7 on 2025-10-11 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_visit_cookies'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('lead_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lead_activity',
            },
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('lead_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
                ('is_automated', models.BooleanField()),
                ('during_work_hours', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lead_task',
            },
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_interest',
        ),
        migrations.RemoveField(
            model_name='leadnextaction',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='leadnextaction',
            name='next_action',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='actions',
        ),
        migrations.CreateModel(
            name='LeadActivityHistory',
            fields=[
                ('lead_activity_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
                ('lead_activity', models.ForeignKey(db_column='lead_activity_id', on_delete=django.db.models.deletion.RESTRICT, to='core.leadactivity')),
            ],
            options={
                'db_table': 'lead_activity_history',
            },
        ),
        migrations.CreateModel(
            name='LeadTaskHistory',
            fields=[
                ('lead_task_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_scheduled', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
                ('lead_task', models.ForeignKey(db_column='lead_task_id', on_delete=django.db.models.deletion.RESTRICT, to='core.leadtask')),
            ],
            options={
                'db_table': 'lead_task_history',
            },
        ),
        migrations.DeleteModel(
            name='LeadInterest',
        ),
        migrations.DeleteModel(
            name='LeadNextAction',
        ),
        migrations.DeleteModel(
            name='NextAction',
        ),
    ]
