# Generated by Django 5.1.7 on 2025-10-16 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_leadactivity_leadtask_remove_lead_lead_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteServiceChangeHistory',
            fields=[
                ('quote_change_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Added', 'Added'), ('Removed', 'Removed')], max_length=10)),
                ('units', models.FloatField()),
                ('price_per_unit', models.FloatField()),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.RESTRICT, to='core.service')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_service_change_history',
            },
        ),
    ]
