# Generated by Django 5.1.7 on 2025-10-16 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_quoteservicechangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteservicechangehistory',
            name='quote',
            field=models.ForeignKey(db_column='quote_id', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='changes', to='core.quote'),
            preserve_default=False,
        ),
    ]
