# Generated by Django 5.1.7 on 2025-10-19 03:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_quoteservicechangehistory_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('event_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Onboarding', 'Onboarding'), ('Awaiting Client Confirmation', 'Awaiting Client Confirmation'), ('Confirmed', 'Confirmed'), ('Awaiting Staff Assignment', 'Awaiting Staff Assignment'), ('Onboarding Completed', 'Onboarding Completed'), ('In Progress', 'In Progress'), ('Extended', 'Extended'), ('Service Completed', 'Service Completed')], max_length=60)),
            ],
            options={
                'db_table': 'event_status',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('event_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.event')),
            ],
            options={
                'db_table': 'event_document',
            },
        ),
        migrations.CreateModel(
            name='EventStatusHistory',
            fields=[
                ('event_status_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.event')),
                ('event_status', models.ForeignKey(db_column='event_status_id', on_delete=django.db.models.deletion.RESTRICT, to='core.eventstatus')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_status_history',
            },
        ),
    ]
