# Generated by Django 5.1.7 on 2025-10-19 03:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_eventstatus_event_external_id_eventdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
