# Generated by Django 5.1.7 on 2025-10-27 23:02

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_event_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(db_column='event_status_id', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='current_events', to='core.eventstatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.quote'),
        ),
        migrations.CreateModel(
            name='AdSpend',
            fields=[
                ('ad_spend_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('spend', models.FloatField()),
                ('ad', models.ForeignKey(db_column='ad_id', on_delete=django.db.models.deletion.CASCADE, related_name='spend_entries', to='core.ad')),
            ],
            options={
                'db_table': 'ad_spend',
            },
        ),
        migrations.CreateModel(
            name='EventTaskLog',
            fields=[
                ('event_task_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField(null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('duration_seconds', models.FloatField(null=True)),
                ('triggered_by', models.CharField(default='cron', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('event', models.ForeignKey(db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='core.event')),
            ],
            options={
                'db_table': 'event_task_log',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['action'], name='event_task__action_04fe43_idx'), models.Index(fields=['status'], name='event_task__status_8cec64_idx'), models.Index(fields=['started_at'], name='event_task__started_687577_idx')],
            },
        ),
    ]
