# Generated by Django 5.1.7 on 2025-10-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_event_event_status_event_quote_adspend_eventtasklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='id',
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
