# Generated by Django 5.1.7 on 2025-11-01 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_remove_ad_id_alter_ad_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(db_column='event_status_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='current_events', to='core.eventstatus'),
        ),
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
