# Generated by Django 5.1.7 on 2025-11-03 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_event_event_status_alter_event_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAdjustment',
            fields=[
                ('price_adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'price_adjustment',
            },
        ),
        migrations.CreateModel(
            name='ServicePriceAdustment',
            fields=[
                ('service_price_adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_adjustment', models.ForeignKey(db_column='price_adjusment_id', on_delete=django.db.models.deletion.CASCADE, to='core.priceadjustment')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'db_table': 'service_price_adjustment',
            },
        ),
    ]
