# Generated by Django 5.1.7 on 2025-11-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_priceadjustment_servicepriceadustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adspend',
            name='ad',
        ),
        migrations.AddField(
            model_name='adspend',
            name='platform_id',
            field=models.IntegerField(choices=[(1, 'Google'), (2, 'Facebook')], default=1),
            preserve_default=False,
        ),
    ]
