# Generated by Django 5.2.8 on 2026-01-18 05:31

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_remove_adspend_ad_adspend_platform_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='BusinessSegment',
            fields=[
                ('business_segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('segment', models.CharField(choices=[('Bartending', 'Bartending'), ('Rentals', 'Rentals')], max_length=15)),
            ],
            options={
                'db_table': 'business_segment',
            },
        ),
        migrations.CreateModel(
            name='DriverStopStatus',
            fields=[
                ('driver_stop_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Allocated', 'Allocated'), ('Out For Delivery', 'Out For Delivery'), ('Completed', 'Completed'), ('Delivery Failed', 'Delivery Failed')], max_length=60)),
            ],
            options={
                'db_table': 'driver_stop_status',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('item_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'item_category',
            },
        ),
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('item_state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('Reserved', 'Reserved'), ('Returned', 'Returned'), ('Purchased', 'Purchased'), ('Sold', 'Sold'), ('Decommissioned', 'Decommissioned')], max_length=25, unique=True)),
            ],
            options={
                'db_table': 'item_state',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('order_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Cancelled', 'Order Cancelled'), ('Awaiting Preparation', 'Awaiting Preparation'), ('Ready for Dispatch', 'Ready For Dispatch'), ('Dispatched', 'Dispatched'), ('Finalized', 'Finalized'), ('Delivery Failed', 'Delivery Failed'), ('Pending Review of Delivery', 'Pending Review Of Delivery'), ('Delivered', 'Delivered'), ('Pending Pick Up', 'Pending Pick Up'), ('Picked Up', 'Picked Up'), ('Customer Picked Up', 'Customer Picked Up'), ('Pending Customer Return', 'Pending Customer Return'), ('Customer Returned', 'Customer Returned')], max_length=60, unique=True)),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='OrderTask',
            fields=[
                ('order_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(choices=[('Load Order Items', 'Load Order Items'), ('Unload Order Items', 'Unload Order Items')], max_length=30)),
            ],
            options={
                'db_table': 'order_task',
            },
        ),
        migrations.CreateModel(
            name='OrderTaskStatus',
            fields=[
                ('order_task_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Unable To Complete', 'Unable To Complete'), ('Completed', 'Completed')], max_length=30)),
            ],
            options={
                'db_table': 'order_task_status',
            },
        ),
        migrations.CreateModel(
            name='RouteZone',
            fields=[
                ('route_zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_fee', models.FloatField()),
            ],
            options={
                'db_table': 'route_zone',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='url',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='business_segment',
            field=models.ForeignKey(db_column='business_segment_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='landing_pages', to='core.businesssegment'),
        ),
        migrations.CreateModel(
            name='DriverRoute',
            fields=[
                ('driver_route_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('target_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='driver_routes', to=settings.AUTH_USER_MODEL)),
                ('route_zone', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='driver_routes', to='core.routezone')),
            ],
            options={
                'db_table': 'driver_route',
            },
        ),
        migrations.CreateModel(
            name='DriverStop',
            fields=[
                ('driver_stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('web_tracking_link', models.TextField(null=True)),
                ('driver_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.driverroute')),
            ],
            options={
                'db_table': 'driver_stop',
            },
        ),
        migrations.CreateModel(
            name='DriverStopImage',
            fields=[
                ('driver_stop_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=core.utils.media_upload_path)),
                ('driver_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.driverstop')),
            ],
            options={
                'db_table': 'driver_stop_image',
            },
        ),
        migrations.CreateModel(
            name='DriverStopStatusChangeHistory',
            fields=[
                ('driver_stop_status_change_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('driver_stop', models.ForeignKey(db_column='driver_stop_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='core.driverstop')),
                ('driver_stop_status', models.ForeignKey(db_column='driver_stop_status_id', on_delete=django.db.models.deletion.RESTRICT, to='core.driverstopstatus')),
            ],
            options={
                'db_table': 'driver_stop_status_change_history',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('item_category', models.ForeignKey(db_column='item_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.itemcategory')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('has_delivery', models.BooleanField(default=True)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.lead')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('order_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup')], max_length=60)),
                ('time_window', models.CharField(choices=[('Exact', 'Exact Time'), ('Flex', 'Flexible (4-hour window)')], max_length=60)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('address', models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.RESTRICT, to='core.address')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.order')),
            ],
            options={
                'db_table': 'order_address',
            },
        ),
        migrations.AddField(
            model_name='driverstop',
            name='order_address',
            field=models.OneToOneField(db_column='order_address_id', on_delete=django.db.models.deletion.CASCADE, to='core.orderaddress'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('units', models.PositiveIntegerField()),
                ('price_per_unit', models.FloatField()),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderItemChangeHistory',
            fields=[
                ('order_item_change_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Added', 'Added'), ('Removed', 'Removed')], max_length=10)),
                ('units', models.PositiveIntegerField()),
                ('price_per_unit', models.FloatField()),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.RESTRICT, to='core.item')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.RESTRICT, related_name='item_changes', to='core.order')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_item_change_history',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('order_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.FloatField()),
                ('price_per_unit', models.FloatField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.order')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.RESTRICT, to='core.service')),
            ],
            options={
                'db_table': 'order_service',
            },
        ),
        migrations.CreateModel(
            name='OrderServiceChangeHistory',
            fields=[
                ('order_service_change_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Added', 'Added'), ('Removed', 'Removed')], max_length=10)),
                ('units', models.FloatField()),
                ('price_per_unit', models.FloatField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.RESTRICT, related_name='service_changes', to='core.order')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.RESTRICT, to='core.service')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_service_change_history',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusChangeHistory',
            fields=[
                ('order_status_change_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.RESTRICT, related_name='changes', to='core.order')),
                ('status', models.ForeignKey(db_column='order_status_id', on_delete=django.db.models.deletion.RESTRICT, to='core.orderstatus')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_status_change_history',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderTaskLog',
            fields=[
                ('order_task_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(null=True)),
                ('assigned_to', models.ForeignKey(db_column='completed_by', on_delete=django.db.models.deletion.RESTRICT, related_name='order_tasks', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.order')),
                ('order_task', models.ForeignKey(db_column='order_task_id', on_delete=django.db.models.deletion.RESTRICT, to='core.ordertask')),
                ('order_task_status', models.ForeignKey(db_column='order_task_status_id', on_delete=django.db.models.deletion.RESTRICT, to='core.ordertaskstatus')),
            ],
            options={
                'db_table': 'order_task_log',
            },
        ),
        migrations.CreateModel(
            name='ServiceBusinessSegment',
            fields=[
                ('service_business_segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_segment', models.ForeignKey(db_column='business_segment', on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='core.businesssegment')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.RESTRICT, to='core.service')),
            ],
            options={
                'db_table': 'service_business_segment',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Driver', 'Driver'), ('Warehouse Staff', 'Warehouse Staff')], max_length=60)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zip_code', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='core.city')),
            ],
            options={
                'db_table': 'zip_code',
            },
        ),
        migrations.AddField(
            model_name='routezone',
            name='zip_code',
            field=models.ForeignKey(db_column='zip_code', on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='core.zipcode'),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.ForeignKey(db_column='zip_code', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.zipcode'),
        ),
        migrations.CreateModel(
            name='ItemStateChangeHistory',
            fields=[
                ('item_state_change_history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('target_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='core.item')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.itemstate')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
            options={
                'db_table': 'item_state_change_history',
                'ordering': ['target_date', 'item_state_change_history_id'],
                'indexes': [models.Index(fields=['item', 'target_date'], name='item_state__item_id_ee1593_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='driverroute',
            constraint=models.UniqueConstraint(fields=('user', 'target_date'), name='unique_driver_per_date'),
        ),
    ]
