# Generated by Django 5.2.8 on 2026-01-26 01:06

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_populate_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBillingContact',
            fields=[
                ('order_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_billing_contact',
            },
        ),
        migrations.CreateModel(
            name='OrderContact',
            fields=[
                ('order_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_contact',
            },
        ),
        migrations.CreateModel(
            name='OrderTaskChoice',
            fields=[
                ('order_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(choices=[('Load Order Items', 'Load Order Items'), ('Unload Order Items', 'Unload Order Items')], max_length=30)),
            ],
            options={
                'db_table': 'order_task_type',
            },
        ),
        migrations.CreateModel(
            name='OrderTaskStatusChangeHistory',
            fields=[
                ('order_task_status_change_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'order_task_status_change_history',
            },
        ),
        migrations.RemoveField(
            model_name='ordertasklog',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='ordertasklog',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordertasklog',
            name='order_task',
        ),
        migrations.RemoveField(
            model_name='ordertasklog',
            name='order_task_status',
        ),
        migrations.AddField(
            model_name='ordertask',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertask',
            name='order',
            field=models.ForeignKey(db_column='order_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertask',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('address_line_1', 'address_line_2', 'zip_code'), name='unique_address_per_zip'),
        ),
        migrations.AddField(
            model_name='orderbillingcontact',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_contact', to='core.order'),
        ),
        migrations.AddField(
            model_name='ordercontact',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_contact', to='core.order'),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='task',
            field=models.ForeignKey(db_column='order_task_choice_id', on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='core.ordertaskchoice'),
        ),
        migrations.AddField(
            model_name='ordertaskstatuschangehistory',
            name='order_task',
            field=models.ForeignKey(db_column='order_task_id', on_delete=django.db.models.deletion.RESTRICT, to='core.ordertask'),
        ),
        migrations.AddField(
            model_name='ordertaskstatuschangehistory',
            name='order_task_status',
            field=models.ForeignKey(db_column='order_task_status_id', on_delete=django.db.models.deletion.RESTRICT, to='core.ordertaskstatus'),
        ),
        migrations.DeleteModel(
            name='OrderTaskLog',
        ),
    ]
