# Generated by Django 5.2.8 on 2026-01-26 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_orderbillingcontact_ordercontact_ordertaskchoice_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordertaskchoice',
            table='order_task_choice',
        ),
    ]
