# Generated by Django 5.2.8 on 2026-01-26 04:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20260125_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbillingcontact',
            old_name='order_contact_id',
            new_name='order_billing_contact_id',
        ),
        migrations.AddField(
            model_name='ordercontact',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercontact',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='core.order'),
        ),
    ]
