# Generated by Django 5.2.8 on 2026-01-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_rename_order_contact_id_orderbillingcontact_order_billing_contact_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertaskchoice',
            old_name='order_task_id',
            new_name='order_task_choice_id',
        ),
    ]
