# Generated by Django 5.2.8 on 2026-01-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_rename_order_task_id_ordertaskchoice_order_task_choice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='ydvendingllc@gmail.com', max_length=254),
        ),
    ]
