# Generated by Django 5.2.8 on 2026-01-27 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryVehicle',
            fields=[
                ('delivery_vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('truck_code', models.CharField(db_index=True, max_length=4, unique=True)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'delivery_vehicle',
            },
        ),
        migrations.CreateModel(
            name='DeliveryVehicleStatus',
            fields=[
                ('delivery_vehicle_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Assigned', 'Assigned'), ('Ready For Dispatch', 'Ready For Dispatch'), ('On The Road', 'On The Road'), ('Inactive', 'Inactive')], max_length=30)),
            ],
            options={
                'db_table': 'delivery_vehicle_status',
            },
        ),
        migrations.AlterField(
            model_name='ordertaskchoice',
            name='task',
            field=models.CharField(choices=[('Load Order Items', 'Load Order Items'), ('Prepare Pickup Order Items', 'Prepare Pickup Order Items'), ('Unload Order Items', 'Unload Order Items')], max_length=30),
        ),
        migrations.CreateModel(
            name='DeliveryVehicleStatusChangeHistory',
            fields=[
                ('delivery_vehicle_status_change_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(db_column='delivery_vehicle_status_id', on_delete=django.db.models.deletion.RESTRICT, to='core.deliveryvehiclestatus')),
                ('vehicle', models.ForeignKey(db_column='delivery_vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.deliveryvehicle')),
            ],
            options={
                'db_table': 'delivery_vehicle_status_change_history',
            },
        ),
    ]
