# Generated by Django 5.2.8 on 2026-01-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_populate_delivery_vehicle_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryvehicle',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
