# Generated by Django 5.1.7 on 2025-05-07 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('referrer', models.URLField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('session_duration', models.FloatField(default=0.0)),
                ('lead_marketing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.leadmarketing')),
            ],
            options={
                'db_table': 'visit',
            },
        ),
    ]
