# Generated by Django 5.1.7 on 2025-04-15 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_lead_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTrackingNumber',
            fields=[
                ('call_tracking_number_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_id', models.IntegerField(choices=[(1, 'Google'), (2, 'Facebook')])),
                ('call_tracking_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'call_tracking_number',
            },
        ),
        migrations.CreateModel(
            name='ConversionLog',
            fields=[
                ('conversion_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.URLField()),
                ('payload', models.TextField()),
                ('status_code', models.IntegerField()),
                ('response', models.TextField(null=True)),
                ('conversion_service_type_id', models.IntegerField(choices=[(1, 'Google'), (2, 'Facebook')])),
            ],
            options={
                'db_table': 'conversion_log',
            },
        ),
        migrations.CreateModel(
            name='InstantForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant_form_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('landing_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.SlugField()),
                ('template', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'landing_page',
            },
        ),
        migrations.CreateModel(
            name='MarketingAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.BigIntegerField()),
                ('headline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CallTracking',
            fields=[
                ('call_tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_assigned', models.DateTimeField()),
                ('date_expires', models.DateTimeField()),
                ('client_id', models.TextField()),
                ('click_id', models.TextField()),
                ('call_tracking_number', models.ForeignKey(db_column='call_tracking_number_id', on_delete=django.db.models.deletion.CASCADE, related_name='call_trackings', to='marketing.calltrackingnumber')),
            ],
            options={
                'db_table': 'call_tracking',
            },
        ),
        migrations.CreateModel(
            name='LeadMarketing',
            fields=[
                ('lead_marketing_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255, null=True)),
                ('medium', models.CharField(max_length=255, null=True)),
                ('channel', models.CharField(max_length=255, null=True)),
                ('landing_page', models.TextField(null=True)),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('referrer', models.TextField(null=True)),
                ('click_id', models.TextField(null=True, unique=True)),
                ('client_id', models.TextField(null=True, unique=True)),
                ('language', models.CharField(max_length=50, null=True)),
                ('button_clicked', models.CharField(max_length=255, null=True)),
                ('device_type', models.CharField(max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('external_id', models.TextField(null=True, unique=True)),
                ('instant_form_lead_id', models.BigIntegerField(null=True)),
                ('instant_form', models.ForeignKey(db_column='instant_form_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_marketing', to='marketing.instantform')),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='lead_marketing', to='core.lead')),
                ('marketing_ad', models.ForeignKey(db_column='marketing_ad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_marketing', to='marketing.marketingad')),
            ],
            options={
                'db_table': 'lead_marketing',
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_campaign_id', models.BigIntegerField()),
                ('platform_id', models.IntegerField(choices=[(1, 'Google'), (2, 'Facebook')])),
            ],
            options={
                'unique_together': {('marketing_campaign_id', 'platform_id')},
            },
        ),
        migrations.AddField(
            model_name='calltrackingnumber',
            name='marketing_campaign',
            field=models.ForeignKey(db_column='marketing_campaign_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_tracking_numbers', to='marketing.marketingcampaign'),
        ),
        migrations.CreateModel(
            name='MarketingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField()),
                ('name', models.TextField()),
                ('marketing_campaign', models.ForeignKey(db_column='marketing_campaign_id', on_delete=django.db.models.deletion.CASCADE, related_name='marketing_groups', to='marketing.marketingcampaign')),
            ],
        ),
        migrations.AddField(
            model_name='marketingad',
            name='marketing_group',
            field=models.ForeignKey(db_column='marketing_group_id', on_delete=django.db.models.deletion.CASCADE, related_name='marketing_ads', to='marketing.marketinggroup'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('referrer', models.URLField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('session_duration', models.FloatField(default=0.0)),
                ('lead_marketing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='marketing.leadmarketing')),
            ],
            options={
                'db_table': 'visit',
            },
        ),
    ]
