# Generated by Django 5.1.7 on 2025-04-16 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmarketing',
            name='marketing_ad',
        ),
        migrations.RemoveField(
            model_name='marketinggroup',
            name='marketing_campaign',
        ),
        migrations.RemoveField(
            model_name='calltrackingnumber',
            name='platform_id',
        ),
        migrations.RemoveField(
            model_name='leadmarketing',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='leadmarketing',
            name='language',
        ),
        migrations.AddField(
            model_name='calltracking',
            name='external_id',
            field=models.CharField(db_index=True, default='dfdsfdsfssdfs', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadmarketing',
            name='marketing_campaign',
            field=models.ForeignKey(db_column='marketing_campaign_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_marketing', to='marketing.marketingcampaign'),
        ),
        migrations.AlterField(
            model_name='calltracking',
            name='click_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='calltracking',
            name='client_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='leadmarketing',
            name='external_id',
            field=models.CharField(db_index=True, default='fsdfsdfsdfds', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MarketingAd',
        ),
        migrations.DeleteModel(
            name='MarketingGroup',
        ),
    ]
