# Generated by Django 5.1.7 on 2025-04-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lead_created_at'),
        ('marketing', '0002_remove_leadmarketing_marketing_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmarketing',
            name='lead',
            field=models.OneToOneField(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='lead_marketing', to='core.lead'),
        ),
    ]
