# Generated by Django 5.1.7 on 2025-04-13 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('cocktail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cocktail',
            },
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('event_role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event_role',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField()),
                ('date_paid', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('tip', models.FloatField(null=True)),
                ('guests', models.IntegerField()),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.lead')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventCocktail',
            fields=[
                ('event_cocktail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cocktail', models.ForeignKey(db_column='cocktail_id', on_delete=django.db.models.deletion.CASCADE, to='crm.cocktail')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='crm.event')),
            ],
            options={
                'db_table': 'event_cocktail',
                'unique_together': {('cocktail', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='cocktails',
            field=models.ManyToManyField(related_name='events', through='crm.EventCocktail', to='crm.cocktail'),
        ),
        migrations.CreateModel(
            name='EventStaff',
            fields=[
                ('event_staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hourly_rate', models.FloatField()),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='crm.event')),
                ('event_role', models.ForeignKey(db_column='event_role_id', on_delete=django.db.models.deletion.RESTRICT, to='crm.eventrole')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_staff',
            },
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('cocktail', models.ForeignKey(db_column='cocktail_id', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='crm.cocktail')),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_cocktails', to='crm.ingredient')),
                ('unit', models.ForeignKey(db_column='unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_cocktails', to='crm.unit')),
            ],
            options={
                'db_table': 'cocktail_ingredient',
                'unique_together': {('cocktail', 'ingredient', 'unit')},
            },
        ),
    ]
