# Generated by Django 5.1.7 on 2025-05-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cocktailingredient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cocktailingredient',
            name='cocktail',
        ),
        migrations.RemoveField(
            model_name='cocktailingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='cocktailingredient',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='CocktailIngredient',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
