# Generated by Django 5.1.7 on 2025-04-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_event_date_created_alter_event_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
